name: Run specs
on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby 2.7
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - name: Run specs
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        run: bundle exec rspec

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.organization=readytech
            -Dsonar.projectKey=rdytech_patches
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.sources=lib/
            -Dsonar.inclusions=**/*.rb
            -Dsonar.tests=spec/
            -Dsonar.ruby.coverage.reportPaths=coverage/.resultset.json
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
